# -*- coding: utf-8 -*-

"""Compatibility facade that exposes the split startup/helper interfaces."""

import atexit
import os

from ._system_paths import (
    PROJECT_ROOT,
    DEFAULT_LOG_ROOT_DIR,
    DEFAULT_SYSTEM_LOG_DIR,
    DEFAULT_SYSTEM_LOG_FILE,
    get_project_root,
    _normalize_project_relative_path,
    get_logs_root_directory,
    get_logs_directory,
    get_default_log_file,
    _resolve_cleanup_patterns,
    resolve_logging_target_paths,
    _collect_matching_files,
    cleanup_log_directory,
    cleanup_logs_on_startup,
    cleanup_old_logs,
    cleanup_project_pycache_dirs,
)
from ._system_state import (
    create_async_queue,
    get_active_threads_safe,
    is_main_process,
    get_process_info,
    get_system_info,
    log_system_info,
    is_free_threading_enabled,
    assert_free_threading_or_exit,
    get_thread_info,
    register_system_state,
    get_memory_usage,
)
from ._system_logging import (
    logger,
    custom_loggers,
    LOGGING_CONFIG,
    THREAD_LOGGING_SELECTION,
    LOGGING_RUNTIME_STATE,
    _resolve_log_level,
    _config_dict_get,
    set_allowed_modules,
    allow_all_modules,
    set_module_level,
    disable_module_logging,
    enable_module_logging,
    set_rotation_config,
    apply_thread_selection_config,
    set_allowed_threads,
    allow_all_threads,
    set_thread_level,
    disable_thread_logging,
    enable_thread_logging,
    set_log_path_config,
    set_startup_cleanup_config,
    set_retention_cleanup_config,
    _log_startup_cleanup_result,
    configure_logging_from_app_config,
    setup_logging,
    get_logger,
    log_level_test,
    configure_logging_for_production,
)
from ._system_lifecycle import (
    run_in_thread,
    run_coroutine,
    create_queue_broker_thread,
    log_imported_modules,
    log_python_pip_versions,
    check_system_processes,
    initialize_system,
    cleanup_system,
)

log_profile = os.environ.get('LOG_PROFILE', 'default')

__all__ = (
    'logger',
    'custom_loggers',
    'LOGGING_CONFIG',
    'THREAD_LOGGING_SELECTION',
    'LOGGING_RUNTIME_STATE',
    'log_profile',
    'PROJECT_ROOT',
    'DEFAULT_LOG_ROOT_DIR',
    'DEFAULT_SYSTEM_LOG_DIR',
    'DEFAULT_SYSTEM_LOG_FILE',
    'get_project_root',
    '_normalize_project_relative_path',
    'get_logs_root_directory',
    'get_logs_directory',
    'get_default_log_file',
    'create_async_queue',
    'get_active_threads_safe',
    'is_main_process',
    'get_process_info',
    '_resolve_log_level',
    'set_allowed_modules',
    'allow_all_modules',
    'set_module_level',
    'disable_module_logging',
    'enable_module_logging',
    'set_rotation_config',
    'apply_thread_selection_config',
    'set_allowed_threads',
    'allow_all_threads',
    'set_thread_level',
    'disable_thread_logging',
    'enable_thread_logging',
    'set_log_path_config',
    'set_startup_cleanup_config',
    'set_retention_cleanup_config',
    '_config_dict_get',
    '_resolve_cleanup_patterns',
    'resolve_logging_target_paths',
    '_collect_matching_files',
    'cleanup_log_directory',
    'cleanup_logs_on_startup',
    '_log_startup_cleanup_result',
    'configure_logging_from_app_config',
    'cleanup_old_logs',
    'cleanup_project_pycache_dirs',
    'setup_logging',
    'get_logger',
    'log_level_test',
    'get_system_info',
    'log_system_info',
    'run_in_thread',
    'run_coroutine',
    'is_free_threading_enabled',
    'assert_free_threading_or_exit',
    'get_thread_info',
    'register_system_state',
    'get_memory_usage',
    'create_queue_broker_thread',
    'configure_logging_for_production',
    'log_imported_modules',
    'log_python_pip_versions',
    'check_system_processes',
    'initialize_system',
    'cleanup_system',
)

_atexit_registered = False
if not _atexit_registered:
    atexit.register(cleanup_system)
    _atexit_registered = True
